language: python
python:
  - '3.5'
sudo: false
env:
  global:
    - secure: "DUk/Ihg8KbbzEgPF0qrHqlxU8e8eET9i/BtzNvFddIGX4HP/P2qz0nk3cVkmjuWhqJXSbC22RdKME9qqPzw6fJwJ6dpJ3OR6dDmSd7rewavq+niwxu52PVa+yK8mL4yf1terM7QQ5tIRf+yUL9qGKrZ2xyvEuRit6d4cFep43Ws="
  matrix:
    - BUILD_SOC=none
    - BUILD_SOC=pipistrello-nist_qc1
    - BUILD_SOC=kc705-nist_qc1
    - BUILD_SOC=kc705-nist_qc2
install:
  - mkdir -p $HOME/.m-labs
  - if [ $TRAVIS_PULL_REQUEST != false ]; then BUILD_SOC=none; fi
  - if [ $BUILD_SOC != none ]; then ./.travis/get-xilinx.sh; fi
  - if [ $BUILD_SOC != none ]; then ./.travis/get-toolchain.sh; fi
  - . ./.travis/get-anaconda.sh
  - source $HOME/miniconda/bin/activate py35
  - conda install -q pip coverage anaconda-client cython
  - pip install coveralls
  # workaround for https://github.com/conda/conda-build/issues/466
  - mkdir -p /home/travis/miniconda/conda-bld/linux-64
  - conda index /home/travis/miniconda/conda-bld/linux-64
script:
  - conda build --python 3.5 conda/artiq
  - conda install -q --use-local artiq
  - |
      if [ $BUILD_SOC == none ]; then
        PACKAGES="$(conda build --output --python 3.5 conda/artiq) $PACKAGES"
        coverage run --source=artiq setup.py test
        make -C doc/manual html
      else
        PACKAGES="$(conda build --output --python 3.5 conda/artiq-$BUILD_SOC) $PACKAGES"
        conda build --python 3.5 conda/artiq-$BUILD_SOC
      fi
after_success:
  - |
      if [ "$TRAVIS_BRANCH" == "master" -a "$PACKAGES" != "" ]; then
        anaconda -q login --hostname $(hostname) --username $binstar_login --password $binstar_password
        anaconda -q upload --user $binstar_login --channel dev $PACKAGES
        anaconda -q logout
      fi
  - coveralls
notifications:
  email:
    recipients:
      - rjordens@nist.gov
    on_success: always
    on_failure: never
  irc:
    channels:
      - chat.freenode.net#m-labs
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Build details : %{build_url}"
