[package]
authors = ["M-Labs"]
name = "runtime"
version = "0.0.0"
build = "build.rs"

[lib]
name = "runtime"
crate-type = ["staticlib"]
path = "lib.rs"

[build-dependencies]
build_artiq = { path = "../libbuild_artiq" }

[dependencies]
byteorder = { version = "1.0", default-features = false }
cslice = { version = "0.3" }
log = { version = "0.3", default-features = false }
alloc_list = { path = "../liballoc_list" }
std_artiq = { path = "../libstd_artiq", features = ["alloc", "io_error_alloc"] }
logger_artiq = { path = "../liblogger_artiq" }
board = { path = "../libboard", features = ["uart_console"] }
proto = { path = "../libproto", features = ["log"] }
amp = { path = "../libamp" }
drtioaux = { path = "../libdrtioaux" }

[dependencies.compiler_builtins]
git = "https://github.com/rust-lang-nursery/compiler-builtins"
rev = "631b568"
features = ["mem"]

[dependencies.fringe]
git = "https://github.com/m-labs/libfringe"
rev = "bd23494"
default-features = false
features = ["alloc"]

[dependencies.smoltcp]
git = "https://github.com/m-labs/smoltcp"
rev = "6f5ae33"
default-features = false
features = ["alloc", "log"]
